blank_issues_enabled: false
contact_links:
  - name: 💬 Preguntas Generales y Discusiones
    url: https://github.com/SamsarDev/samsar-site/discussions
    about: ¿Tenés una consulta general o querés compartir un pensamiento? Abrí una discusión aquí.
